### PR TITLE
ci: add test step to integration workflow

### PR DESCRIPTION
**Pull request by iamfj**
In this pull request, I've made significant updates to the `integration.yml` workflow to enhance the efficiency and clarity of our CI/CD process. Key changes include:

1. **Separation of Build and Test Steps:** The workflow has been restructured to distinctly separate 'build' and 'test' steps. This modification ensures a more organized and logical flow, where the build process is now contingent on the successful completion of tests.

2. **Dependency Management:** The 'build' step is configured to depend on the 'test' step. This means that the build process will only commence once all tests have passed, ensuring that we only build with tested and verified code.

3. **Inclusion of Setup Node Action:** The workflow now includes the 'setup node' action, which is instrumental in ensuring that our environment is correctly configured for both testing and building processes.

4. **Comprehensive Testing:** The 'test' job has been expanded to include both linting and unit tests. This comprehensive testing approach enhances code quality and reliability.

5. **Removal of Linting from the Build Job:** Previously, linting was a part of the build job. It has now been moved to the test job, streamlining the build process and maintaining a clear separation of concerns.

These changes aim to improve the overall efficiency and effectiveness of our CI/CD pipeline, ensuring a higher standard of code quality and reliability in our development process.

### CODE REVIEW

**Comment by iamludal** [comment]
Hi, thanks for your contribution. I have 2 questions regarding your changes:
1. Do we really need to separate the build and test job? What is the benefit that we get? The workflow is quite simple, and we actually lose time setting up 2 runners, cloning the repo twice, etc.
2. Why do we need the pull_request and pull_request_target events? The push event should be sufficient as the GitHub check will automatically show up on the Pull Request, since the push and Pull Request branches are the same.

**Comment by iamfj** [comment]
> Hi, thanks for your contribution. I have 2 questions regarding your changes:
> 
> 1. Do we really need to separate the build and test job? What is the benefit that we get? The workflow is quite simple, and we actually lose time setting up 2 runners, cloning the repo twice, etc.
> 2. Why do we need the pull_request and pull_request_target events? The push event should be sufficient as the GitHub check will automatically show up on the Pull Request, since the push and Pull Request branches are the same.

Good point. I separated it out of habit, but you're absolutely right, unnecessary complexity. I refactor it and just add the tests, that should be enough.

Thanks for your feedback!

**Comment by iamfj** [comment]
But i have discovered another weird thing. Any ideas?

https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1

```
$ jest
/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:1131
        throw new Error('Parameter token or opts.auth is required');
        ^

Error: Parameter token or opts.auth is required
    at Object.getAuthString (/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:1131:15)
    at Object.getOctokitOptions (/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:1202:24)
    at Object.getOctokit (/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:1095:42)
    at 1314 (/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:11[6](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:7)39:28)
    at __nccwpck_require__ (/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:11851:43)
    at 399 (/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:11556:28)
    at __nccwpck_require__ (/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:11851:43)
    at /home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:118[7](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:8)1:37
    at Object.<anonymous> (/home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js:11[8](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:9)74:12)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)

Node.js v18.1[9](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:10).0
FAIL tests/main.test.ts
  ✕ test runs (76 ms)

  ● test runs

    Command failed: /usr/local/bin/node /home/runner/work/action-purge-workflow-runs/action-purge-workflow-runs/dist/index.js

      [12](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:13) |     stdio: 'inherit',
      [13](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:14) |   }
    > [14](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:15) |   cp.execFileSync(np, [ip], options)
         |      ^
      [15](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:16) | })
      [16](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:17) |

      at Object.<anonymous> (tests/main.test.ts:14:6)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.[30](https://github.com/iamfj/action-purge-workflow-runs/actions/runs/7452084040/job/20274581446?pr=1#step:5:31)9 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Review by iamludal — APPROVED** [review]

**Comment by iamludal** [comment]
Approved! Thanks again for your contribution.
Do you still have the error? Or everything is ok now?

**Comment by iamfj** [comment]
I still have the error in my fork workflow. But let's fix it later!

**Comment by iamludal** [comment]
It seems like the problem also happens on my workflow, can you have a look please?
I think this is because the test suite is creating an instance of `octokit` without providing a GitHub Token.
We might want to provide a dummy token (via the `GITHUB_TOKEN` env var) and mock methods of the `octokit` client.

**Comment by iamfj** [comment]
> It seems like the problem also happens on my workflow, can you have a look please? I think this is because the test suite is creating an instance of `octokit` without providing a GitHub Token. We might want to provide a dummy token (via the `GITHUB_TOKEN` env var) and mock methods of the `octokit` client.

Alright, ill have a look.

**Comment by iamfj** [comment]
Hej @iamludal, apologies for the delayed response; the past few weeks have been quite hectic. I hope you're doing well.

Regarding the issue with `main.test.ts`, I believe it's closely tied to the project setup. Upon reviewing the test, it appears to function more like an integration test rather than a traditional unit test, primarily due to its strong dependency on the project setup. This dependency might be causing issues, possibly related to incorrect permissions. The functionality works well when executed locally, but there appears to be a permissions issue when it's run within the GitHub workflow. It's also possible that this issue is related to my fork of the project. Forks typically have different permissions compared to the original project, which could be influencing the behavior we're observing.

To address this, I recommend refactoring `main.test.ts`. We could separate it into distinct unit tests and integration tests. By doing so, we can create a more isolated and controlled environment for each type of test, which would improve the reliability and clarity of our testing process.

If you need assistance with this or have further insights, please feel free to share.

**Comment by iamludal** [comment]
Hi @iamfj, apologies for the late reply too. Thanks again for contributing to this project.
Are there any simpler solutions, like providing a dummy token as I suggested? And mocking octokit methods

**Comment by iamfj** [comment]
I understand that the recent weeks have likely been quite demanding for you as well. I am confident that we can mock the octocat API, specifically targeting the endpoints relevant to our action. Nevertheless, I also see the value in conducting integration testing, utilizing either an actual API token or a simulated one, if feasible. 

I will investigate this further and provide you with an update on my findings.

**Comment by iamludal** [comment]
No problem, you can work on this and suggest your changes once done. I don't see any problem in conducting integration testing. I was just looking for a quick win to fix the issue, but feel free to work on this. :)

**Comment by iamfj** [comment]
@iamludal, it appears that I have identified a temporary solution by incorporating the `GITHUB_TOKEN` into the testing job. 🎉 But i would like to refactor those tests in another PR. What do you say? Is it now also working on your workflow run?

**Comment by iamludal** [comment]
Hi @iamfj! It almost works, I still have an error.
image
By the way, I think we should try to mock now, otherwise the test step will erase some of the workflow runs on this repository (which is not a big deal, but not what we wanted). What do you think about it?

**Comment by iamludal** [comment]
@iamfj Nevermind, it works, it was a wrong configuration in the repository settings. I'll approve the PR but we should definitely mock octokit calls 😄

**Comment by iamfj** [comment]
I agree with you on that. I can take care of it, but rather in a new PR.

**Comment by iamfj** [comment]
@iamludal For your information, I have corrected the commit messages to adhere to the conventional commit message standards.

**Comment by iamludal** [comment]
@iamfj many thanks, I'm merging the PR

**Pull request merged**
